version: '3'

services:

  postgres:
    image: postgres:9.6
    domainname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgres:5432/userDB -schemas=hiber -user=postgres -password=postgres -connectRetries=30 migrate
    volumes:
      - ./lesson6/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

